name: Build and Package Windows Release

on:
  push:
    branches: [ master ] # Optional: Keep building on pushes to main (creates artifact only)
    tags:
      - 'v*'        # *** TRIGGER on tags starting with 'v' (e.g., v1.0, v1.0.2) ***
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write # Needed to create/upload releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Compile Java code
      shell: cmd
      run: |
        echo "Creating bin directory..."
        mkdir bin
        echo "Generating sources list..."
        dir /s /b src\*.java > sources.txt
        echo "Compiling..."
        javac -d bin -cp "Dependencies\*" @sources.txt
        if %errorlevel% neq 0 exit /b %errorlevel%
        echo "Compilation successful."

    - name: Create run script
      shell: cmd
      run: |
        echo @echo off > run-esuite.bat
        echo java -cp ".;bin;Dependencies\*" gui.Principal >> run-esuite.bat
        echo pause >> run-esuite.bat

    - name: Package application into ZIP
      shell: powershell
      run: |
        # Extract version from tag (e.g., refs/tags/v1.0.2 becomes v1.0.2)
        # Use a fallback name for non-tag triggers
        if ($env:GITHUB_REF -like 'refs/tags/v*') {
          $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        } else {
          $version = "dev-${{ github.run_number }}"
        }
        $assetName = "eSuite-${version}.zip"
        Compress-Archive -Path bin, Dependencies, icons, Imagenes, config.txt, Example.ris, lgpl.txt, README.md, termicas.txt, ThermodynamicalProperties.txt, run-esuite.bat -DestinationPath $assetName -Force
        echo "ASSET_NAME=$assetName" >> $env:GITHUB_ENV # Share asset name with later steps
        echo "Created $assetName"

    # Upload artifact for ALL runs (pushes, tags, manual) for inspection/testing
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: eSuite-Windows-Package
        path: ${{ env.ASSET_NAME }}

    # *** Create/Update GitHub Release ONLY for tag pushes ***
    - name: Create/Update GitHub Release
      # Only run this step if the trigger was a tag push starting with 'v'
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        # tag_name: ${{ github.ref_name }} # Uses the tag that triggered the workflow
        files: ${{ env.ASSET_NAME }} # The ZIP file created earlier
        # You can add options like 'body', 'name', 'draft', 'prerelease' here
        # Example: Create a draft release named after the tag
        # name: "Release ${{ github.ref_name }}"
        # draft: true
        # prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Uses the default token provided by GitHub