name: Build and Package Windows Release

on:
  push:
    branches: [ master ] # Optional: Build on pushes to master (creates artifact only)
    tags:
      - 'v*'        # TRIGGER on tags starting with 'v' (e.g., v1.0, v1.0.2)
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner

    permissions:
      contents: write # Needed to create/upload releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetches all history so tags are available

    # --- UPDATED: Use JDK 8 ---
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8' # Specify Java 8
        distribution: 'temurin' # Using Eclipse Temurin distribution (formerly AdoptOpenJDK)

    # --- UPDATED: Add encoding flag ---
    - name: Compile Java code
      shell: cmd
      run: |
        echo "Creating bin directory..."
        mkdir bin
        echo "Generating sources list..."
        dir /s /b src\*.java > sources.txt
        echo "Compiling with JDK 8..."
        javac -encoding UTF-8 -d bin -cp "Dependencies\*" @sources.txt
        if %errorlevel% neq 0 exit /b %errorlevel%
        echo "Compilation successful."

    - name: Create run script
      shell: cmd
      run: |
        echo @echo off > run-esuite.bat
        echo rem Requires Java 8 Runtime Environment (JRE 8) in PATH or JAVA_HOME >> run-esuite.bat
        echo java -cp ".;bin;Dependencies\*" gui.Principal >> run-esuite.bat
        echo pause >> run-esuite.bat

    - name: Package application into ZIP
      shell: powershell
      run: |
        # Extract version from tag or set default
        if ($env:GITHUB_REF -like 'refs/tags/v*') {
          $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        } else {
          $version = "dev-${{ github.run_number }}"
        }
        $assetName = "eSuite-${version}.zip"
        Compress-Archive -Path bin, Dependencies, icons, Imagenes, config.txt, examples, lgpl.txt, README.md, termicas.txt, ThermodynamicalProperties.txt, run-esuite.bat -DestinationPath $assetName -Force
        echo "ASSET_NAME=$assetName" >> $env:GITHUB_ENV # Share asset name with later steps
        echo "VERSION=$version" >> $env:GITHUB_ENV # Share version with later steps
        echo "Created Application ZIP: $assetName"

    - name: Prepare Chocolatey package source
      shell: powershell
      run: |
        # Create the structure expected by choco pack
        New-Item -Path 'choco-pkg-src' -ItemType Directory -Force
        New-Item -Path 'choco-pkg-src\tools' -ItemType Directory -Force
        # Copy the nuspec and ps1 scripts from the repo (assuming they are in ./chocolatey)
        if (Test-Path -Path 'chocolatey\engineeringsuite.nuspec') {
            Copy-Item -Path 'chocolatey\engineeringsuite.nuspec' -Destination 'choco-pkg-src\'
        } else {
            Write-Error "engineeringsuite.nuspec not found in ./chocolatey directory"
            exit 1
        }
        if (Test-Path -Path 'chocolatey\tools\chocolateyInstall.ps1') {
            Copy-Item -Path 'chocolatey\tools\*' -Destination 'choco-pkg-src\tools\'
        } else {
             Write-Error "Chocolatey install/uninstall scripts not found in ./chocolatey/tools directory"
             exit 1
        }
        # Copy necessary files for embedding (into the package's tools dir)
        Copy-Item -Path "${{ env.ASSET_NAME }}" -Destination 'choco-pkg-src\tools\' # Copy the already created zip
        Copy-Item -Path 'lgpl.txt' -Destination 'choco-pkg-src\tools\'
        Copy-Item -Path 'icons\logo.png' -Destination 'choco-pkg-src\tools\'
        echo "Chocolatey package source prepared in choco-pkg-src"

    - name: Build Chocolatey Package
      shell: powershell
      run: |
        # Determine version from nuspec
        [xml]$nuspec = Get-Content -Path "choco-pkg-src\engineeringsuite.nuspec"
        $nuspecVersion = $nuspec.package.metadata.version
        Write-Host "Version found in nuspec: $nuspecVersion"

        # Run choco pack
        cd choco-pkg-src
        Write-Host "Running choco pack..."
        choco pack
        if ($LASTEXITCODE -ne 0) { Write-Error "choco pack failed!"; exit 1 }
        Write-Host "Choco pack succeeded."

        # Validate and move nupkg
        $expectedNupkgPath = "engineeringsuite.${nuspecVersion}.nupkg"
        Write-Host "Expected NUPKG path: $expectedNupkgPath"
        if (-not (Test-Path -Path $expectedNupkgPath -PathType Leaf)) { Write-Error "Packed file '$expectedNupkgPath' not found!"; Get-ChildItem -Path .; exit 1 }
        $nupkgName = "engineeringsuite.${nuspecVersion}.nupkg"
        Write-Host "Moving '$expectedNupkgPath' to '..\${nupkgName}'"
        Move-Item -Path $expectedNupkgPath -Destination "..\${nupkgName}" -Force
        echo "CHOCO_PKG_NAME=$nupkgName" >> $env:GITHUB_ENV
        cd ..
        echo "Created Chocolatey package: $nupkgName"

    - name: Upload build artifacts (ZIP and NUPKG)
      uses: actions/upload-artifact@v4
      with:
        name: eSuite-Windows-Build-${{ env.VERSION }}
        path: |
          ${{ env.ASSET_NAME }}
          ${{ env.CHOCO_PKG_NAME }}

    - name: Create/Update GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ env.ASSET_NAME }}
          ${{ env.CHOCO_PKG_NAME }}
        name: "Engineering Suite ${{ env.VERSION }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}